<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="helloworld_tests.HelloWorldTest-20240313093429" tests="1" file="helloworld_tests.py" time="0.001" timestamp="2024-03-13T09:34:29" failures="0" errors="1" skipped="0">
	<testcase classname="helloworld_tests.HelloWorldTest" name="test_should_issue_hello_world_message" time="0.001" timestamp="2024-03-13T09:34:29">
		<error type="NameError" message="name 'hellworld' is not defined"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/balatha/programs/devops/pyb/src/unittest/python/helloworld_tests.py", line 9, in test_should_issue_hello_world_message
    hellworld(out)
NameError: name 'hellworld' is not defined
]]></error>
	</testcase>
</testsuite>
